import { StyleSheet } from "react-native";
import { Colors, screenHeight } from "../utils/Constants";

export const connectionStyles = StyleSheet.create({
    container: {
        marginTop: 10,
        padding: 16,
    },
    connectionContainer: {
        marginTop: 20,
        padding: 14,
        flexDirection: "row",
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: Colors.surface,
        borderRadius: 18,
        borderWidth: 1,
        borderColor: Colors.border,
        shadowColor: Colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 10,
        elevation: 3,
    },
    sendReceiveButton: {
        paddingHorizontal: 12,
        borderRadius: 10,
        paddingVertical: 6,
        gap: 6,
        flexDirection: 'row',
        alignItems: "center",
    },
    disconnectButton: {
        paddingHorizontal: 14,
        paddingVertical: 8,
        backgroundColor: '#FEF2F2',
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: "center",
        justifyContent: 'center',
        gap: 6,
        borderWidth: 1,
        borderColor: '#FEE2E2',
    },
    fileContainer: {
        backgroundColor: Colors.surface,
        borderRadius: 20,
        marginTop: 20,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: Colors.border,
        shadowColor: Colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 12,
        elevation: 3,
    },
    sendReceiveContainer: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        borderBottomWidth: 1,
        padding: 12,
        borderBottomColor: Colors.border_light,
        backgroundColor: Colors.card,
    },
    activeButton: {
        backgroundColor: Colors.primary,
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 6,
        shadowColor: Colors.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 2,
    },
    inactiveButton: {
        backgroundColor: Colors.surface,
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 6,
        borderWidth: 1,
        borderColor: Colors.border,
    },
    sendReceiveButtonContainer: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    sendReceiveDataContainer: {
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
        backgroundColor: Colors.secondary,
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
    },
    sendRecieveButton: {
        paddingHorizontal: 12,
        backgroundColor: Colors.surface,
        borderRadius: 8,
        paddingVertical: 6,
        gap: 6,
        flexDirection: 'row',
        alignItems: "center",
    },
    fileItem: {
        flexDirection: 'row',
        alignItems: "center",
        justifyContent: 'space-between',
        padding: 14,
        backgroundColor: Colors.surface,
        borderBottomWidth: 1,
        borderBottomColor: Colors.border_light,
    },
    fileInfoContainer: {
        flexDirection: 'row',
        alignItems: "center",
        flex: 1,
    },
    fileIconWrapper: {
        width: 40,
        height: 40,
        borderRadius: 12,
        backgroundColor: Colors.secondary,
        justifyContent: 'center',
        alignItems: 'center',
    },
    fileDetails: {
        marginLeft: 12,
        flex: 1,
    },
    openButton: {
        backgroundColor: Colors.primary,
        borderRadius: 20,
        paddingVertical: 6,
        paddingHorizontal: 16,
        justifyContent: 'center',
        alignItems: "center",
        shadowColor: Colors.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 2,
    },
    fileList: {
        minHeight: 180,
    },
    noDataContainer: {
        height: screenHeight * 0.35,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    }
});