import { StyleSheet } from "react-native";
import { Colors, screenWidth } from "../utils/Constants";

export const sendStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.primary,
    },
    mainContainer: {
        flex: 1,
    },
    deviceDot: {
        position: 'absolute',
        justifyContent: 'center',
        alignItems: 'center',
    },
    popup: {
        justifyContent: 'center',
        alignItems: 'center',
        maxWidth: 120,
    },
    deviceImage: {
        width: 38,
        height: 38,
        borderRadius: 19,
        borderWidth: 2,
        borderColor: '#fff',
        shadowColor: Colors.primary_dark,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
    },
    deviceText: {
        textAlign: 'center',
        paddingVertical: 3,
        paddingHorizontal: 8,
        borderRadius: 12,
        maxWidth: 140,
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        borderWidth: 1,
        borderColor: Colors.border,
        marginTop: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 3,
        elevation: 2,
    },
    radarContainer: {
        position: 'absolute',
        width: screenWidth,
        height: screenWidth,
        justifyContent: 'center',
        alignItems: 'center',
    },
    backButton: {
        padding: 8,
        borderRadius: 100,
        zIndex: 4,
        position: "absolute",
        top: 14,
        left: 14,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.18,
        elevation: 4,
        shadowRadius: 6,
        shadowColor: Colors.primary,
        backgroundColor: Colors.surface,
        borderWidth: 1,
        borderColor: Colors.border,
    },
    infoContainer: {
        margin: 20,
        marginTop: 50,
        justifyContent: "center",
        alignItems: "center",
    },
    lottieContainer: {
        position: "absolute",
        zIndex: 4,
        width: "100%",
        height: "100%",
        alignSelf: "center",
    },
    lottie: {
        width: "100%",
        height: "100%",
    },
    animationContainer: {
        width: "100%",
        justifyContent: "center",
        alignItems: "center",
        height: screenWidth,
    },
    profileImage: {
        height: 56,
        width: 56,
        resizeMode: "cover",
        borderRadius: 28,
        zIndex: 5,
        borderWidth: 3,
        borderColor: '#fff',
        shadowColor: Colors.primary_dark,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    qrButton: {
        backgroundColor: Colors.surface,
        paddingVertical: 12,
        paddingHorizontal: 24,
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "row",
        gap: 8,
        borderRadius: 30,
        borderWidth: 1,
        borderColor: Colors.border,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        elevation: 5,
        shadowRadius: 10,
        shadowColor: Colors.primary,
    },
});
